runfile('/home/ubuntu/Documents/yolo/detection_yolo/main.py', wdir='/home/ubuntu/Documents/yolo/detection_yolo')
AUTO_EXPOSURE = 1.0
EXPOSURE      = 60.0
🔄 En attente que le serveur soit prêt sur 192.168.0.103:65432 (max 300s) :.........
✅ Serveur détecté !
Connexion en cours...
✅ Connecté au serveur
❌ Connexion réinitialisée par le serveur.
❌ Aucune couleur d'équipe reçue dans le délai imparti ou erreur réseau.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1